title: 주간 업무 보고 
labels: ["Announcements"]
body:
  - type: markdown
    attributes:
      value: |
        ### 이번 주
        수행해야 할 업무 목록입니다
  - type: textarea
    id: this_cj
    attributes:
      label: 찬준
      description: "이번 주 업무 입력"
      value: |
        - [ ] task1
      render:
    validations:
      required: false

  - type: textarea
    id: this_ny
    attributes:
      label: 나연
      description: "이번 주 업무 입력"
      value: |
        - [ ] task1
      render:
    validations:
      required: false
      
  - type: textarea
    id: this_sm
    attributes:
      label: 수민
      description: "이번 주 업무 입력"
      value: |
        - [ ] task1
      render:
    validations:
      required: false
      
  - type: textarea
    id: this_jo
    attributes:
      label: 재욱
      description: "이번 주 업무 입력"
      value: |
        - [ ] task1
      render:
    validations:
      required: false
