title: 주간 업무 보고 
labels: ["Announcements"]
body:
  - type: markdown
    attributes:
      value: "## 지난 주"
        
  - type: textarea
    id: last_cj
    attributes:
      label: 찬준
      description: "지난 주 업무 입력"
      value: .
      render:
    validations:
      required: false

  - type: textarea
    id: last_ny
    attributes:
      label: 나연
      description: "지난 주 업무 입력"
      value: .
      render:
    validations:
      required: false
      
  - type: textarea
    id: last_sm
    attributes:
      label: 수민
      description: "지난 주 업무 입력"
      value: .
      render:
    validations:
      required: false
      
  - type: textarea
    id: last_jo
    attributes:
      label: 재욱
      description: "지난 주 업무 입력"
      value: .
      render:
    validations:
      required: false

  - type: markdown
    attributes:
      value: "## 이번 주"

  - type: textarea
    id: this_cj
    attributes:
      label: 찬준
      description: "이번 주 업무 입력"
      value: .
      render:
    validations:
      required: false

  - type: textarea
    id: this_ny
    attributes:
      label: 나연
      description: "이번 주 업무 입력"
      value: .
      render:
    validations:
      required: false
      
  - type: textarea
    id: this_sm
    attributes:
      label: 수민
      description: "이번 주 업무 입력"
      value: .
      render:
    validations:
      required: false
      
  - type: textarea
    id: this_jo
    attributes:
      label: 재욱
      description: "이번 주 업무 입력"
      value: .
      render:
    validations:
      required: false
