name: API Docs Integration

on:
  push:
    branches:
      - master

jobs:
  api-docs-integration:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: 'master'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Set up Nodejs legacy
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Grant execute permission for gradlew
        run: |
          chmod +x ./gradlew

      - name: gradle task
        run: |
          ./gradlew generateOpenApiDocs

      - name : collect json
        run : |
          cp ./build/openapi.json ./

      - name: redoc-cli join
        uses: DeltaLaboratory/redocly-cli-action@
        with:
          args: 'join *.json -o api.yaml'

      - name: check result
        run: |
          ls -al
          test -f api.yaml || (echo "Missing api.yaml from previous step." && exit 1)

      - name: redoc-cli build docs
        uses: DeltaLaboratory/redocly-cli-action@v1.0.0
        with:
          args: 'build-docs api.yaml -o index.html'

      - name: check result
        run: |
          ls -al
          test -f index.html || (echo "Missing index.html from previous step." && exit 1)

      - name: Install SSH Key
        uses: leigholiver/commit-with-deploy-key@v1.0.4
        with:
          source: index.html
          destination_folder: docs
          destination_repo: ${{ github.repository }}
          destination_branch: master
          deploy_key: ${{ secrets.DEPLOY_KEY }}